config/routes.rb
Rails.application.routes.draw do
  resources :restaurants do
    resources :reviews
  end

end

app/models/restaurant.rb
class Restaurant < ActiveRecord::Base
	has_many :reviews
	validates :name, presence: true, length: { minimum: 3 }


	def average_rating
		return 'N/A' if reviews.none?
		reviews.average(:rating)
	end

end

app/models/review.rb
class Review < ActiveRecord::Base
	belongs_to :restaurant
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/restaurants_controller.rb
class RestaurantsController < ApplicationController
	def index
		@restaurants = Restaurant.all
		@review = Review.new
	end

    # GET /restaurants/new HTTP/1.1
	def new
		@restaurant = Restaurant.new
	end

    # POST /restaurants HTTP/1.1 (see rake routes)
	def create
		@restaurant = Restaurant.new restaurant_params 

		if @restaurant.save
		  redirect_to '/restaurants'
		else
		  render 'new'
		end
	end

	def edit
		@restaurant = Restaurant.find params[:id]
	end

	def update
		@restaurant = Restaurant.find params[:id]
		
	    if @restaurant.update restaurant_params

		  redirect_to '/restaurants'
		else
		  render 'edit'
		end
	end

	def restaurant_params
		params.require(:restaurant).permit(:name)
	end

	def destroy
		@restaurant = Restaurant.find params[:id]
		@restaurant.destroy
		flash[:notice] = 'Restaurant successfully deleted'
		redirect_to '/restaurants'
	end

end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController

	def new
		@restaurant = Restaurant.find params[:restaurant_id]
		@review = Review.new
	end

	def create
		# @restaurant = Restaurant.find params[:restaurant_id]
  #    	@review = @restaurant.reviews.create params[:review].permit(:content, :rating)
 
     	flash[:notice] = 'Review created!'
		Review.create(restaurant_id: params[:restaurant_id], rating: params[:review][:rating], content: params[:review][:content])
    	redirect_to '/restaurants'
   end

# params.require(:restaurant).permit(:name)

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/restaurants_helper.rb
module RestaurantsHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper

	def star_rating(rating)
		return rating unless rating.is_a? Numeric
		hollow_stars = "☆" * (5 - rating.round)
		("★" * rating.round) + hollow_stars
	end

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Yelp</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

  <%= notice %>
  <%= yield %>

</body>
</html>

app/views/restaurants/_errors.html.erb
<% if @restaurant.errors %>
	You have the following errors:
	<% @restaurant.errors.full_messages.each do |error| %>
		<%= error %>
	<% end %>
<% end %>

app/views/restaurants/_form.html.erb
<%= form_for @restaurant do |f| %>
	<%= f.label :name %>
	<%= f.text_field :name %>

	<%= f.submit %>
<% end %>

<%= render 'errors' %>

app/views/restaurants/edit.html.erb
Edit a restaurant:

<%= render 'form' %>

app/views/restaurants/index.html.erb
<% if @restaurants.any? %>
	<% @restaurants.each do |restaurant| %>
		<p/>
		<%= restaurant.name %>
		<p/>
		Average rating: <%= star_rating(restaurant.average_rating) %>
		<p/>
		<%= link_to("Edit #{restaurant.name}", edit_restaurant_path(restaurant.id)) %>
		<%= link_to("Delete #{restaurant.name}", restaurant_path(restaurant.id), method: :delete) %>
		<%= link_to("Review #{restaurant.name}", new_restaurant_review_path(restaurant.id) )%>	
		<% restaurant.reviews.each do |review| %>
		<p/>
			<%=	review.content %>: <%= star_rating(review.rating) %> 
		<% end %>		
		<%= form_for [restaurant, @review] do |review| %>
			<%= review.label :content %>
			<%= review.text_area :content %>

			<%= review.label :rating %>
			<%= review.select :rating, 1..5 %>

			<%= review.submit %>
		<% end %>
	<% end %>
<% else %>
	No restaurants
<% end %>

app/views/restaurants/new.html.erb
Create a restaurant:

<%= render 'form' %>

app/views/reviews/new.html.erb
<%= form_for [@restaurant, @review] do |review| %>
	<%= review.label :content %>
	<%= review.text_area :content %>

	<%= review.label :rating %>
	<%= review.select :rating, 1..5 %>

	<%= review.submit %>
<% end %>